# Generated by Django 4.2.23 on 2025-07-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_followers_posts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="imageURL",
            field=models.URLField(blank=True, null=True),
        ),
    ]
